using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DomainLayer
{
    public class MarketingDocumentLines
    {
        [Key]
        public int Id { get; set; }
        public string Session { get; set; }
        public string User { get; set; }
        public string SapField { get; set; }
        public string DocEntry { get; set; }
        public string LineNum { get; set; }
        public string TargetType { get; set; }
        public string TrgetEntry { get; set; }
        public string BaseRef { get; set; }
        public string BaseType { get; set; }
        public string BaseEntry { get; set; }
        public string BaseLine { get; set; }
        public string LineStatus { get; set; }
        public string ItemCode { get; set; }
        public string ItemCode2 { get; set; }
        public string WarehouseCode { get; set; }
        public string FromWarehouseCode { get; set; }
        public string Dscription { get; set; }
        public string Quantity { get; set; }
        public string ShipDate { get; set; }
        public string OpenQty { get; set; }
        public string ProjectCode { get; set; }
        public string Price { get; set; }
        public string Currency { get; set; }
        public string Rate { get; set; }
        public string DiscPrcnt { get; set; }
        public string LineTotal { get; set; }
        public string TotalFrgn { get; set; }
        public string OpenSum { get; set; }
        public string OpenSumFC { get; set; }
        public string VendorNum { get; set; }
        public string SerialNum { get; set; }
        public string WhsCode { get; set; }
        public string SlpCode { get; set; }
        public string Commission { get; set; }
        public string TreeType { get; set; }
        public string AcctCode { get; set; }
        public string TaxStatus { get; set; }
        public string GrossBuyPr { get; set; }
        public string PriceBefDi { get; set; }
        public string DocDate { get; set; }
        public string Flags { get; set; }
        public string OpenCreQty { get; set; }
        public string UseBaseUn { get; set; }
        public string SubCatNum { get; set; }
        public string BaseCard { get; set; }
        public string TotalSumSy { get; set; }
        public string OpenSumSys { get; set; }
        public string InvntSttus { get; set; }
        public string OcrCode { get; set; }
        public string Project { get; set; }
        public string CodeBars { get; set; }
        public string VatPrcnt { get; set; }
        public string VatGroup { get; set; }
        public string PriceAfVAT { get; set; }
        public string Height1 { get; set; }
        public string Hght1Unit { get; set; }
        public string Height2 { get; set; }
        public string Hght2Unit { get; set; }
        public string Width1 { get; set; }
        public string Wdth1Unit { get; set; }
        public string Width2 { get; set; }
        public string Wdth2Unit { get; set; }
        public string Length1 { get; set; }
        public string Len1Unit { get; set; }
        public string length2 { get; set; }
        public string Len2Unit { get; set; }
        public string Volume { get; set; }
        public string VolUnit { get; set; }
        public string Weight1 { get; set; }
        public string Wght1Unit { get; set; }
        public string Weight2 { get; set; }
        public string Wght2Unit { get; set; }
        public string Factor1 { get; set; }
        public string Factor2 { get; set; }
        public string Factor3 { get; set; }
        public string Factor4 { get; set; }
        public string PackQty { get; set; }
        public string UpdInvntry { get; set; }
        public string BaseDocNum { get; set; }
        public string BaseAtCard { get; set; }
        public string SWW { get; set; }
        public string VatSum { get; set; }
        public string VatSumFrgn { get; set; }
        public string VatSumSy { get; set; }
        public string FinncPriod { get; set; }
        public string ObjType { get; set; }
        public string LogInstanc { get; set; }
        public string BlockNum { get; set; }
        public string ImportLog { get; set; }
        public string DedVatSum { get; set; }
        public string DedVatSumF { get; set; }
        public string DedVatSumS { get; set; }
        public string IsAqcuistn { get; set; }
        public string DistribSum { get; set; }
        public string DstrbSumFC { get; set; }
        public string DstrbSumSC { get; set; }
        public string GrssProfit { get; set; }
        public string GrssProfSC { get; set; }
        public string GrssProfFC { get; set; }
        public string VisOrder { get; set; }
        public string INMPrice { get; set; }
        public string PoTrgNum { get; set; }
        public string PoTrgEntry { get; set; }
        public string DropShip { get; set; }
        public string PoLineNum { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string OrigItem { get; set; }
        public string BackOrdr { get; set; }
        public string FreeTxt { get; set; }
        public string PickStatus { get; set; }
        public string PickOty { get; set; }
        public string PickIdNo { get; set; }
        public string TrnsCode { get; set; }
        public string VatAppld { get; set; }
        public string VatAppldFC { get; set; }
        public string VatAppldSC { get; set; }
        public string BaseQty { get; set; }
        public string BaseOpnQty { get; set; }
        public string VatDscntPr { get; set; }
        public string WtLiable { get; set; }
        public string DeferrTax { get; set; }
        public string EquVatPer { get; set; }
        public string EquVatSum { get; set; }
        public string EquVatSumF { get; set; }
        public string EquVatSumS { get; set; }
        public string LineVat { get; set; }
        public string LineVatlF { get; set; }
        public string LineVatS { get; set; }
        public string unitMsr { get; set; }
        public string NumPerMsr { get; set; }
        public string CEECFlag { get; set; }
        public string ToStock { get; set; }
        public string ToDiff { get; set; }
        public string ExciseAmt { get; set; }
        public string TaxPerUnit { get; set; }
        public string TotInclTax { get; set; }
        public string CountryOrg { get; set; }
        public string StckDstSum { get; set; }
        public string ReleasQtty { get; set; }
        public string LineType { get; set; }
        public string TranType { get; set; }
        public string Text { get; set; }
        public string OwnerCode { get; set; }
        public string StockPrice { get; set; }
        public string ConsumeFCT { get; set; }
        public string LstByDsSum { get; set; }
        public string StckINMPr { get; set; }
        public string LstBINMPr { get; set; }
        public string StckDstFc { get; set; }
        public string StckDstSc { get; set; }
        public string LstByDsFc { get; set; }
        public string LstByDsSc { get; set; }
        public string StockSum { get; set; }
        public string StockSumFc { get; set; }
        public string StockSumSc { get; set; }
        public string StckSumApp { get; set; }
        public string StckAppFc { get; set; }
        public string StckAppSc { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToDesc { get; set; }
        public string StckAppD { get; set; }
        public string StckAppDFC { get; set; }
        public string StckAppDSC { get; set; }
        public string BasePrice { get; set; }
        public string GTotal { get; set; }
        public string GTotalFC { get; set; }
        public string GTotalSC { get; set; }
        public string DistribExp { get; set; }
        public string DescOW { get; set; }
        public string DetailsOW { get; set; }
        public string GrossBase { get; set; }
        public string VatWoDpm { get; set; }
        public string VatWoDpmFc { get; set; }
        public string VatWoDpmSc { get; set; }
        public string CFOPCode { get; set; }
        public string CSTCode { get; set; }
        public string Usage { get; set; }
        public string TaxOnly { get; set; }
        public string WtCalced { get; set; }
        public string QtyToShip { get; set; }
        public string DelivrdQty { get; set; }
        public string OrderedQty { get; set; }
        public string CogsOcrCod { get; set; }
        public string CiOppLineN { get; set; }
        public string CogsAcct { get; set; }
        public string ChgAsmBoMW { get; set; }
        public string ActDelDate { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string TaxDistSum { get; set; }
        public string TaxDistSFC { get; set; }
        public string TaxDistSSC { get; set; }
        public string PostTax { get; set; }
        public string Excisable { get; set; }
        public string AssblValue { get; set; }
        public string RG23APart1 { get; set; }
        public string RG23APart2 { get; set; }
        public string RG23CPart1 { get; set; }
        public string RG23CPart2 { get; set; }
        public string CogsOcrCo2 { get; set; }
        public string CogsOcrCo3 { get; set; }
        public string CogsOcrCo4 { get; set; }
        public string CogsOcrCo5 { get; set; }
        public string LnExcised { get; set; }
        public string LocCode { get; set; }
        public string StockValue { get; set; }
        public string GPTtlBasPr { get; set; }
        public string unitMsr2 { get; set; }
        public string NumPerMsr2 { get; set; }
        public string SpecPrice { get; set; }
        public string CSTfIPI { get; set; }
        public string CSTfPIS { get; set; }
        public string CSTfCOFINS { get; set; }
        public string ExLineNo { get; set; }
        public string isSrvCall { get; set; }
        public string PQTReqQty { get; set; }
        public string PQTReqDate { get; set; }
        public string PcDocType { get; set; }
        public string PcQuantity { get; set; }
        public string LinManClsd { get; set; }
        public string VatGrpSrc { get; set; }
        public string NoInvtryMv { get; set; }
        public string ActBaseEnt { get; set; }
        public string ActBaseLn { get; set; }
        public string ActBaseNum { get; set; }
        public string OpenRtnQty { get; set; }
        public string AgrNo { get; set; }
        public string AgrLnNum { get; set; }
        public string CredOrigin { get; set; }
        public string Surpluses { get; set; }
        public string DefBreak { get; set; }
        public string Shortages { get; set; }
        public string UomEntry { get; set; }
        public string UomEntry2 { get; set; }
        public string UomCode { get; set; }
        public string UomCode2 { get; set; }
        public string FromWhsCod { get; set; }
        public string NeedQty { get; set; }
        public string PartRetire { get; set; }
        public string RetireQty { get; set; }
        public string RetireAPC { get; set; }
        public string RetirAPCFC { get; set; }
        public string RetirAPCSC { get; set; }
        public string InvQty { get; set; }
        public string OpenInvQty { get; set; }
        public string EnSetCost { get; set; }
        public string RetCost { get; set; }
        public string Incoterms { get; set; }
        public string TransMod { get; set; }
        public string LineVendor { get; set; }
        public string DistribIS { get; set; }
        public string ISDistrb { get; set; }
        public string ISDistrbFC { get; set; }
        public string ISDistrbSC { get; set; }
        public string IsByPrdct { get; set; }
        public string ItemType { get; set; }
        public string PriceEdit { get; set; }
        public string PrntLnNum { get; set; }
        public string LinePoPrss { get; set; }
        public string FreeChrgBP { get; set; }
        public string TaxRelev { get; set; }
        public string LegalText { get; set; }
        public string ThirdParty { get; set; }
        public string LicTradNum { get; set; }
        public string InvQtyOnly { get; set; }
        public string UnencReasn { get; set; }
        public string ShipFromCo { get; set; }
        public string ShipFromDe { get; set; }
        public string FisrtBin { get; set; }
        public string AllocBinC { get; set; }
        public string ExpType { get; set; }
        public string ExpUUID { get; set; }
        public string ExpOpType { get; set; }
        public string DIOTNat { get; set; }
        public string MYFtype { get; set; }
        public string ItmTaxType { get; set; }
        public string SacEntry { get; set; }
        public string NCMCode { get; set; }
        public string U_GrossPrice { get; set; }
        public string U_Qty { get; set; }
        public string U_UOM { get; set; }
        public string U_ActualQty { get; set; }
        public string U_VarianceQty { get; set; }
        public string U_TransType { get; set; }
        public string U_Disc1 { get; set; }
        public string U_Disc2 { get; set; }
        public string U_Disc3 { get; set; }
        public string U_Disc4 { get; set; }
        public string U_Disc5 { get; set; }
        public string U_NetDisc { get; set; }
        public string U_API_Vendor { get; set; }
        public string U_API_TIN { get; set; }
        public string U_API_Address { get; set; }
        public string U_SalesType { get; set; }
        public string U_RGC { get; set; }
        public string U_PONo { get; set; }
        public string U_CustType { get; set; }
        public string U_ORNumber { get; set; }
        public string U_OrderNo { get; set; }
        public string U_DiscType { get; set; }
        public string U_AppStat { get; set; }
        public string U_OwnerCode { get; set; }
        public string U_AllocQty { get; set; }
        public string U_BT_Alloc { get; set; }
        public string U_DS_Alloca { get; set; }
        public string U_CN_Alloc { get; set; }
        public string U_OR_Alloc { get; set; }
        public string U_OL_Alloc { get; set; }
        public string U_MaxInv { get; set; }
        public string U_EmpName { get; set; }
        public string U_Pricetag { get; set; }
        public string U_MOI { get; set; }
        public string U_Remarks { get; set; }
        public string U_Chain { get; set; }
        public string U_PricetagCount { get; set; }
        public string U_POQty { get; set; }
        public string U_CtnQty { get; set; }
        public string U_TargetWhs { get; set; }
        public string U_TrgetWhsName { get; set; }
        public string U_ItemCode { get; set; }
        public string U_Description { get; set; }
        public string U_IssueType { get; set; }
        public string U_Company { get; set; }
        public string U_SKU { get; set; }
        public string U_ItemCost { get; set; }
        public string U_UnitPricePerPiece { get; set; }
        public string U_PreferredSupplier { get; set; }
        public string U_bir_tax_grp { get; set; }
        public string U_Style { get; set; }
        public string U_Color { get; set; }
        public string U_Size { get; set; }
        public string U_SampleCode { get; set; }
        public string U_ItemNo { get; set; }
        public string U_Quantity { get; set; }
        public string U_QuantityInnerBox { get; set; }
        public string U_StyleSubCat { get; set; }
        public string U_RemarksDescription { get; set; }
    }
}
